// AUTO-GENERATED — do not edit by hand.
// Generated from spec/public-api.json

import { apiRequest } from "../lib/api-client.js";
import type { ToolDefinition, ToolHandler, ToolModule } from "../lib/types.js";

const definitions: ToolDefinition[] = [
  {
    name: "connected_organizations_list",
    description: "List all connected organizations",
    inputSchema: {
      type: "object",
      properties: {
            "page": {
                  "type": "string",
                  "description": "between(1, 1000)"
            },
            "per_page": {
                  "type": "string",
                  "description": "between(1, 100)"
            },
            "name": {
                  "type": "string"
            }
      },
    },
  },
  {
    name: "connected_organizations_create",
    description: "Create a connected organization",
    inputSchema: {
      type: "object",
      properties: {
            "name": {
                  "type": "string"
            },
            "dba_name": {
                  "type": "string"
            },
            "ein": {
                  "type": "string"
            },
            "business_email": {
                  "type": "string"
            },
            "candidate_support_email": {
                  "type": "string"
            },
            "phone": {
                  "type": "string"
            },
            "default_language": {
                  "type": "string",
                  "enum": [
                        "af",
                        "ak",
                        "sq",
                        "am",
                        "ar",
                        "hy",
                        "as",
                        "ay",
                        "az",
                        "bm",
                        "bn",
                        "eu",
                        "be",
                        "bho",
                        "bs",
                        "bg",
                        "my",
                        "ca",
                        "ceb",
                        "ckb",
                        "zh-CN",
                        "zh-TW",
                        "co",
                        "hr",
                        "cs",
                        "da",
                        "dv",
                        "doi",
                        "nl",
                        "en",
                        "eo",
                        "et",
                        "ee",
                        "fil",
                        "fi",
                        "fr",
                        "gl",
                        "lg",
                        "ka",
                        "de",
                        "el",
                        "gu",
                        "ht",
                        "ha",
                        "haw",
                        "he",
                        "hi",
                        "hmn",
                        "hu",
                        "is",
                        "ig",
                        "ilo",
                        "id",
                        "ga",
                        "it",
                        "ja",
                        "jv",
                        "kn",
                        "kk",
                        "km",
                        "rw",
                        "kok",
                        "ko",
                        "kri",
                        "ku",
                        "ky",
                        "lo",
                        "la",
                        "lv",
                        "ln",
                        "lt",
                        "lb",
                        "mk",
                        "mai",
                        "mg",
                        "ms",
                        "ml",
                        "mt",
                        "mni-Mtei",
                        "mi",
                        "mr",
                        "lus",
                        "mn",
                        "ne",
                        "nso",
                        "no",
                        "ny",
                        "or",
                        "om",
                        "ps",
                        "fa",
                        "pl",
                        "pt",
                        "pa",
                        "qu",
                        "ro",
                        "ru",
                        "sm",
                        "sa",
                        "gd",
                        "sr",
                        "sn",
                        "sd",
                        "si",
                        "sk",
                        "sl",
                        "so",
                        "st",
                        "es",
                        "su",
                        "sw",
                        "sv",
                        "tg",
                        "ta",
                        "tt",
                        "te",
                        "th",
                        "ti",
                        "ts",
                        "tr",
                        "tk",
                        "uk",
                        "ur",
                        "ug",
                        "uz",
                        "vi",
                        "cy",
                        "fy",
                        "xh",
                        "yi",
                        "yo",
                        "zu"
                  ]
            },
            "supported_languages": {
                  "type": "array",
                  "items": {
                        "type": "string",
                        "enum": [
                              "af",
                              "ak",
                              "sq",
                              "am",
                              "ar",
                              "hy",
                              "as",
                              "ay",
                              "az",
                              "bm",
                              "bn",
                              "eu",
                              "be",
                              "bho",
                              "bs",
                              "bg",
                              "my",
                              "ca",
                              "ceb",
                              "ckb",
                              "zh-CN",
                              "zh-TW",
                              "co",
                              "hr",
                              "cs",
                              "da",
                              "dv",
                              "doi",
                              "nl",
                              "en",
                              "eo",
                              "et",
                              "ee",
                              "fil",
                              "fi",
                              "fr",
                              "gl",
                              "lg",
                              "ka",
                              "de",
                              "el",
                              "gu",
                              "ht",
                              "ha",
                              "haw",
                              "he",
                              "hi",
                              "hmn",
                              "hu",
                              "is",
                              "ig",
                              "ilo",
                              "id",
                              "ga",
                              "it",
                              "ja",
                              "jv",
                              "kn",
                              "kk",
                              "km",
                              "rw",
                              "kok",
                              "ko",
                              "kri",
                              "ku",
                              "ky",
                              "lo",
                              "la",
                              "lv",
                              "ln",
                              "lt",
                              "lb",
                              "mk",
                              "mai",
                              "mg",
                              "ms",
                              "ml",
                              "mt",
                              "mni-Mtei",
                              "mi",
                              "mr",
                              "lus",
                              "mn",
                              "ne",
                              "nso",
                              "no",
                              "ny",
                              "or",
                              "om",
                              "ps",
                              "fa",
                              "pl",
                              "pt",
                              "pa",
                              "qu",
                              "ro",
                              "ru",
                              "sm",
                              "sa",
                              "gd",
                              "sr",
                              "sn",
                              "sd",
                              "si",
                              "sk",
                              "sl",
                              "so",
                              "st",
                              "es",
                              "su",
                              "sw",
                              "sv",
                              "tg",
                              "ta",
                              "tt",
                              "te",
                              "th",
                              "ti",
                              "ts",
                              "tr",
                              "tk",
                              "uk",
                              "ur",
                              "ug",
                              "uz",
                              "vi",
                              "cy",
                              "fy",
                              "xh",
                              "yi",
                              "yo",
                              "zu"
                        ]
                  }
            },
            "address": {
                  "type": "object",
                  "properties": {
                        "street": {
                              "type": "string"
                        },
                        "secondary": {
                              "type": "string"
                        },
                        "city": {
                              "type": "string"
                        },
                        "state": {
                              "type": "string"
                        },
                        "zip": {
                              "type": "string"
                        },
                        "country": {
                              "type": "string",
                              "enum": [
                                    "AND",
                                    "ARE",
                                    "ATG",
                                    "AIA",
                                    "ALB",
                                    "ARM",
                                    "AGO",
                                    "ATA",
                                    "ARG",
                                    "ASM",
                                    "AUT",
                                    "AUS",
                                    "ABW",
                                    "ALA",
                                    "AZE",
                                    "BIH",
                                    "BRB",
                                    "BGD",
                                    "BEL",
                                    "BFA",
                                    "BGR",
                                    "BHR",
                                    "BDI",
                                    "BEN",
                                    "BLM",
                                    "BMU",
                                    "BRN",
                                    "BOL",
                                    "BES",
                                    "BRA",
                                    "BHS",
                                    "BTN",
                                    "BVT",
                                    "BWA",
                                    "BLR",
                                    "BLZ",
                                    "CAN",
                                    "CCK",
                                    "COD",
                                    "CAF",
                                    "COG",
                                    "CHE",
                                    "CIV",
                                    "COK",
                                    "CHL",
                                    "CHN",
                                    "CMR",
                                    "COL",
                                    "CRI",
                                    "CPV",
                                    "CUW",
                                    "CXR",
                                    "CYP",
                                    "CZE",
                                    "DEU",
                                    "DJI",
                                    "DNK",
                                    "DMA",
                                    "DOM",
                                    "DZA",
                                    "ECU",
                                    "EST",
                                    "EGY",
                                    "ESH",
                                    "ERI",
                                    "ESP",
                                    "ETH",
                                    "FIN",
                                    "FJI",
                                    "FLK",
                                    "FSM",
                                    "FRO",
                                    "FRA",
                                    "GAB",
                                    "GBR",
                                    "GRD",
                                    "GEO",
                                    "GUF",
                                    "GGY",
                                    "GHA",
                                    "GIB",
                                    "GRL",
                                    "GMB",
                                    "GIN",
                                    "GLP",
                                    "GNQ",
                                    "GRC",
                                    "SGS",
                                    "GTM",
                                    "GUM",
                                    "GNB",
                                    "GUY",
                                    "HKG",
                                    "HMD",
                                    "HND",
                                    "HRV",
                                    "HTI",
                                    "HUN",
                                    "IDN",
                                    "IRL",
                                    "ISR",
                                    "IMN",
                                    "IND",
                                    "IOT",
                                    "IRQ",
                                    "ISL",
                                    "ITA",
                                    "JEY",
                                    "JAM",
                                    "JOR",
                                    "JPN",
                                    "KEN",
                                    "KGZ",
                                    "KHM",
                                    "KIR",
                                    "COM",
                                    "KNA",
                                    "KOR",
                                    "KWT",
                                    "CYM",
                                    "KAZ",
                                    "LAO",
                                    "LBN",
                                    "LCA",
                                    "LIE",
                                    "LKA",
                                    "LBR",
                                    "LSO",
                                    "LTU",
                                    "LUX",
                                    "LVA",
                                    "LBY",
                                    "MAR",
                                    "MCO",
                                    "MDA",
                                    "MNE",
                                    "MAF",
                                    "MDG",
                                    "MHL",
                                    "MKD",
                                    "MLI",
                                    "MMR",
                                    "MNG",
                                    "MAC",
                                    "MNP",
                                    "MTQ",
                                    "MRT",
                                    "MSR",
                                    "MLT",
                                    "MUS",
                                    "MDV",
                                    "MWI",
                                    "MEX",
                                    "MYS",
                                    "MOZ",
                                    "NAM",
                                    "NCL",
                                    "NER",
                                    "NFK",
                                    "NGA",
                                    "NIC",
                                    "NLD",
                                    "NOR",
                                    "NPL",
                                    "NRU",
                                    "NIU",
                                    "NZL",
                                    "OMN",
                                    "PAN",
                                    "PER",
                                    "PYF",
                                    "PNG",
                                    "PHL",
                                    "PAK",
                                    "POL",
                                    "SPM",
                                    "PCN",
                                    "PRI",
                                    "PSE",
                                    "PRT",
                                    "PLW",
                                    "PRY",
                                    "QAT",
                                    "REU",
                                    "ROU",
                                    "SRB",
                                    "RUS",
                                    "RWA",
                                    "SAU",
                                    "SLB",
                                    "SYC",
                                    "SWE",
                                    "SGP",
                                    "SHN",
                                    "SVN",
                                    "SJM",
                                    "SVK",
                                    "SLE",
                                    "SMR",
                                    "SEN",
                                    "SOM",
                                    "SUR",
                                    "SSD",
                                    "STP",
                                    "SLV",
                                    "SXM",
                                    "SWZ",
                                    "TCA",
                                    "TCD",
                                    "ATF",
                                    "TGO",
                                    "THA",
                                    "TJK",
                                    "TKL",
                                    "TLS",
                                    "TKM",
                                    "TUN",
                                    "TON",
                                    "TUR",
                                    "TTO",
                                    "TUV",
                                    "TWN",
                                    "TZA",
                                    "UKR",
                                    "UGA",
                                    "UMI",
                                    "USA",
                                    "URY",
                                    "UZB",
                                    "VAT",
                                    "VCT",
                                    "VEN",
                                    "VGB",
                                    "VIR",
                                    "VNM",
                                    "VUT",
                                    "WLF",
                                    "WSM",
                                    "YEM",
                                    "MYT",
                                    "ZAF",
                                    "ZMB",
                                    "ZWE"
                              ]
                        },
                        "full_address": {
                              "type": "string"
                        }
                  },
                  "required": [
                        "street",
                        "city",
                        "state",
                        "country",
                        "full_address"
                  ]
            }
      },
      required: ["name","business_email","default_language","supported_languages"],
    },
  },
  {
    name: "connected_organizations_find_by_id",
    description: "Get a connected organization by ID",
    inputSchema: {
      type: "object",
      properties: {
            "uid": {
                  "type": "string",
                  "description": "Connected Organization Identifier"
            }
      },
      required: ["uid"],
    },
  },
  {
    name: "connected_organizations_update_by_id",
    description: "Update a connected organization",
    inputSchema: {
      type: "object",
      properties: {
            "uid": {
                  "type": "string",
                  "description": "Connected Organization Identifier"
            },
            "name": {
                  "type": "string"
            },
            "dba_name": {
                  "type": "string"
            },
            "ein": {
                  "type": "string"
            },
            "business_email": {
                  "type": "string"
            },
            "candidate_support_email": {
                  "type": "string"
            },
            "phone": {
                  "type": "string"
            },
            "default_language": {
                  "type": "string",
                  "enum": [
                        "af",
                        "ak",
                        "sq",
                        "am",
                        "ar",
                        "hy",
                        "as",
                        "ay",
                        "az",
                        "bm",
                        "bn",
                        "eu",
                        "be",
                        "bho",
                        "bs",
                        "bg",
                        "my",
                        "ca",
                        "ceb",
                        "ckb",
                        "zh-CN",
                        "zh-TW",
                        "co",
                        "hr",
                        "cs",
                        "da",
                        "dv",
                        "doi",
                        "nl",
                        "en",
                        "eo",
                        "et",
                        "ee",
                        "fil",
                        "fi",
                        "fr",
                        "gl",
                        "lg",
                        "ka",
                        "de",
                        "el",
                        "gu",
                        "ht",
                        "ha",
                        "haw",
                        "he",
                        "hi",
                        "hmn",
                        "hu",
                        "is",
                        "ig",
                        "ilo",
                        "id",
                        "ga",
                        "it",
                        "ja",
                        "jv",
                        "kn",
                        "kk",
                        "km",
                        "rw",
                        "kok",
                        "ko",
                        "kri",
                        "ku",
                        "ky",
                        "lo",
                        "la",
                        "lv",
                        "ln",
                        "lt",
                        "lb",
                        "mk",
                        "mai",
                        "mg",
                        "ms",
                        "ml",
                        "mt",
                        "mni-Mtei",
                        "mi",
                        "mr",
                        "lus",
                        "mn",
                        "ne",
                        "nso",
                        "no",
                        "ny",
                        "or",
                        "om",
                        "ps",
                        "fa",
                        "pl",
                        "pt",
                        "pa",
                        "qu",
                        "ro",
                        "ru",
                        "sm",
                        "sa",
                        "gd",
                        "sr",
                        "sn",
                        "sd",
                        "si",
                        "sk",
                        "sl",
                        "so",
                        "st",
                        "es",
                        "su",
                        "sw",
                        "sv",
                        "tg",
                        "ta",
                        "tt",
                        "te",
                        "th",
                        "ti",
                        "ts",
                        "tr",
                        "tk",
                        "uk",
                        "ur",
                        "ug",
                        "uz",
                        "vi",
                        "cy",
                        "fy",
                        "xh",
                        "yi",
                        "yo",
                        "zu"
                  ]
            },
            "supported_languages": {
                  "type": "array",
                  "items": {
                        "type": "string",
                        "enum": [
                              "af",
                              "ak",
                              "sq",
                              "am",
                              "ar",
                              "hy",
                              "as",
                              "ay",
                              "az",
                              "bm",
                              "bn",
                              "eu",
                              "be",
                              "bho",
                              "bs",
                              "bg",
                              "my",
                              "ca",
                              "ceb",
                              "ckb",
                              "zh-CN",
                              "zh-TW",
                              "co",
                              "hr",
                              "cs",
                              "da",
                              "dv",
                              "doi",
                              "nl",
                              "en",
                              "eo",
                              "et",
                              "ee",
                              "fil",
                              "fi",
                              "fr",
                              "gl",
                              "lg",
                              "ka",
                              "de",
                              "el",
                              "gu",
                              "ht",
                              "ha",
                              "haw",
                              "he",
                              "hi",
                              "hmn",
                              "hu",
                              "is",
                              "ig",
                              "ilo",
                              "id",
                              "ga",
                              "it",
                              "ja",
                              "jv",
                              "kn",
                              "kk",
                              "km",
                              "rw",
                              "kok",
                              "ko",
                              "kri",
                              "ku",
                              "ky",
                              "lo",
                              "la",
                              "lv",
                              "ln",
                              "lt",
                              "lb",
                              "mk",
                              "mai",
                              "mg",
                              "ms",
                              "ml",
                              "mt",
                              "mni-Mtei",
                              "mi",
                              "mr",
                              "lus",
                              "mn",
                              "ne",
                              "nso",
                              "no",
                              "ny",
                              "or",
                              "om",
                              "ps",
                              "fa",
                              "pl",
                              "pt",
                              "pa",
                              "qu",
                              "ro",
                              "ru",
                              "sm",
                              "sa",
                              "gd",
                              "sr",
                              "sn",
                              "sd",
                              "si",
                              "sk",
                              "sl",
                              "so",
                              "st",
                              "es",
                              "su",
                              "sw",
                              "sv",
                              "tg",
                              "ta",
                              "tt",
                              "te",
                              "th",
                              "ti",
                              "ts",
                              "tr",
                              "tk",
                              "uk",
                              "ur",
                              "ug",
                              "uz",
                              "vi",
                              "cy",
                              "fy",
                              "xh",
                              "yi",
                              "yo",
                              "zu"
                        ]
                  }
            },
            "address": {
                  "type": "object",
                  "properties": {
                        "street": {
                              "type": "string"
                        },
                        "secondary": {
                              "type": "string"
                        },
                        "city": {
                              "type": "string"
                        },
                        "state": {
                              "type": "string"
                        },
                        "zip": {
                              "type": "string"
                        },
                        "country": {
                              "type": "string",
                              "enum": [
                                    "AND",
                                    "ARE",
                                    "ATG",
                                    "AIA",
                                    "ALB",
                                    "ARM",
                                    "AGO",
                                    "ATA",
                                    "ARG",
                                    "ASM",
                                    "AUT",
                                    "AUS",
                                    "ABW",
                                    "ALA",
                                    "AZE",
                                    "BIH",
                                    "BRB",
                                    "BGD",
                                    "BEL",
                                    "BFA",
                                    "BGR",
                                    "BHR",
                                    "BDI",
                                    "BEN",
                                    "BLM",
                                    "BMU",
                                    "BRN",
                                    "BOL",
                                    "BES",
                                    "BRA",
                                    "BHS",
                                    "BTN",
                                    "BVT",
                                    "BWA",
                                    "BLR",
                                    "BLZ",
                                    "CAN",
                                    "CCK",
                                    "COD",
                                    "CAF",
                                    "COG",
                                    "CHE",
                                    "CIV",
                                    "COK",
                                    "CHL",
                                    "CHN",
                                    "CMR",
                                    "COL",
                                    "CRI",
                                    "CPV",
                                    "CUW",
                                    "CXR",
                                    "CYP",
                                    "CZE",
                                    "DEU",
                                    "DJI",
                                    "DNK",
                                    "DMA",
                                    "DOM",
                                    "DZA",
                                    "ECU",
                                    "EST",
                                    "EGY",
                                    "ESH",
                                    "ERI",
                                    "ESP",
                                    "ETH",
                                    "FIN",
                                    "FJI",
                                    "FLK",
                                    "FSM",
                                    "FRO",
                                    "FRA",
                                    "GAB",
                                    "GBR",
                                    "GRD",
                                    "GEO",
                                    "GUF",
                                    "GGY",
                                    "GHA",
                                    "GIB",
                                    "GRL",
                                    "GMB",
                                    "GIN",
                                    "GLP",
                                    "GNQ",
                                    "GRC",
                                    "SGS",
                                    "GTM",
                                    "GUM",
                                    "GNB",
                                    "GUY",
                                    "HKG",
                                    "HMD",
                                    "HND",
                                    "HRV",
                                    "HTI",
                                    "HUN",
                                    "IDN",
                                    "IRL",
                                    "ISR",
                                    "IMN",
                                    "IND",
                                    "IOT",
                                    "IRQ",
                                    "ISL",
                                    "ITA",
                                    "JEY",
                                    "JAM",
                                    "JOR",
                                    "JPN",
                                    "KEN",
                                    "KGZ",
                                    "KHM",
                                    "KIR",
                                    "COM",
                                    "KNA",
                                    "KOR",
                                    "KWT",
                                    "CYM",
                                    "KAZ",
                                    "LAO",
                                    "LBN",
                                    "LCA",
                                    "LIE",
                                    "LKA",
                                    "LBR",
                                    "LSO",
                                    "LTU",
                                    "LUX",
                                    "LVA",
                                    "LBY",
                                    "MAR",
                                    "MCO",
                                    "MDA",
                                    "MNE",
                                    "MAF",
                                    "MDG",
                                    "MHL",
                                    "MKD",
                                    "MLI",
                                    "MMR",
                                    "MNG",
                                    "MAC",
                                    "MNP",
                                    "MTQ",
                                    "MRT",
                                    "MSR",
                                    "MLT",
                                    "MUS",
                                    "MDV",
                                    "MWI",
                                    "MEX",
                                    "MYS",
                                    "MOZ",
                                    "NAM",
                                    "NCL",
                                    "NER",
                                    "NFK",
                                    "NGA",
                                    "NIC",
                                    "NLD",
                                    "NOR",
                                    "NPL",
                                    "NRU",
                                    "NIU",
                                    "NZL",
                                    "OMN",
                                    "PAN",
                                    "PER",
                                    "PYF",
                                    "PNG",
                                    "PHL",
                                    "PAK",
                                    "POL",
                                    "SPM",
                                    "PCN",
                                    "PRI",
                                    "PSE",
                                    "PRT",
                                    "PLW",
                                    "PRY",
                                    "QAT",
                                    "REU",
                                    "ROU",
                                    "SRB",
                                    "RUS",
                                    "RWA",
                                    "SAU",
                                    "SLB",
                                    "SYC",
                                    "SWE",
                                    "SGP",
                                    "SHN",
                                    "SVN",
                                    "SJM",
                                    "SVK",
                                    "SLE",
                                    "SMR",
                                    "SEN",
                                    "SOM",
                                    "SUR",
                                    "SSD",
                                    "STP",
                                    "SLV",
                                    "SXM",
                                    "SWZ",
                                    "TCA",
                                    "TCD",
                                    "ATF",
                                    "TGO",
                                    "THA",
                                    "TJK",
                                    "TKL",
                                    "TLS",
                                    "TKM",
                                    "TUN",
                                    "TON",
                                    "TUR",
                                    "TTO",
                                    "TUV",
                                    "TWN",
                                    "TZA",
                                    "UKR",
                                    "UGA",
                                    "UMI",
                                    "USA",
                                    "URY",
                                    "UZB",
                                    "VAT",
                                    "VCT",
                                    "VEN",
                                    "VGB",
                                    "VIR",
                                    "VNM",
                                    "VUT",
                                    "WLF",
                                    "WSM",
                                    "YEM",
                                    "MYT",
                                    "ZAF",
                                    "ZMB",
                                    "ZWE"
                              ]
                        },
                        "full_address": {
                              "type": "string"
                        }
                  },
                  "required": [
                        "street",
                        "city",
                        "state",
                        "country",
                        "full_address"
                  ]
            }
      },
      required: ["uid"],
    },
  },
  {
    name: "connected_organizations_delete_by_id",
    description: "Delete a connected organization",
    inputSchema: {
      type: "object",
      properties: {
            "uid": {
                  "type": "string",
                  "description": "Connected Organization Identifier"
            }
      },
      required: ["uid"],
    },
  },
];

const handlers: Record<string, ToolHandler> = {
  async connected_organizations_list(args) {
    try {
      const params: Record<string, unknown> = {};
      if (args.page !== undefined) params.page = args.page;
      if (args.per_page !== undefined) params.per_page = args.per_page;
      if (args.name !== undefined) params.name = args.name;
      const result = await apiRequest("GET", "/api/v1/connected_organizations", { params });
      return {
        content: [{
          type: "text" as const,
          text: JSON.stringify(result.data, null, 2),
        }],
      };
    } catch (error) {
      return {
        content: [{
          type: "text" as const,
          text: `Error: ${error instanceof Error ? error.message : String(error)}`,
        }],
      };
    }
  },
  async connected_organizations_create(args) {
    try {
      const body: Record<string, unknown> = {};
      if (args.name !== undefined) body.name = args.name;
      if (args.dba_name !== undefined) body.dba_name = args.dba_name;
      if (args.ein !== undefined) body.ein = args.ein;
      if (args.business_email !== undefined) body.business_email = args.business_email;
      if (args.candidate_support_email !== undefined) body.candidate_support_email = args.candidate_support_email;
      if (args.phone !== undefined) body.phone = args.phone;
      if (args.default_language !== undefined) body.default_language = args.default_language;
      if (args.supported_languages !== undefined) body.supported_languages = args.supported_languages;
      if (args.address !== undefined) body.address = args.address;
      const result = await apiRequest("POST", "/api/v1/connected_organizations", { body });
      return {
        content: [{
          type: "text" as const,
          text: JSON.stringify(result.data, null, 2),
        }],
      };
    } catch (error) {
      return {
        content: [{
          type: "text" as const,
          text: `Error: ${error instanceof Error ? error.message : String(error)}`,
        }],
      };
    }
  },
  async connected_organizations_find_by_id(args) {
    try {
      const pathParams: Record<string, string> = {
        uid: String(args.uid),
      };
      const result = await apiRequest("GET", "/api/v1/connected_organizations/{uid}", { pathParams });
      return {
        content: [{
          type: "text" as const,
          text: JSON.stringify(result.data, null, 2),
        }],
      };
    } catch (error) {
      return {
        content: [{
          type: "text" as const,
          text: `Error: ${error instanceof Error ? error.message : String(error)}`,
        }],
      };
    }
  },
  async connected_organizations_update_by_id(args) {
    try {
      const pathParams: Record<string, string> = {
        uid: String(args.uid),
      };
      const body: Record<string, unknown> = {};
      if (args.name !== undefined) body.name = args.name;
      if (args.dba_name !== undefined) body.dba_name = args.dba_name;
      if (args.ein !== undefined) body.ein = args.ein;
      if (args.business_email !== undefined) body.business_email = args.business_email;
      if (args.candidate_support_email !== undefined) body.candidate_support_email = args.candidate_support_email;
      if (args.phone !== undefined) body.phone = args.phone;
      if (args.default_language !== undefined) body.default_language = args.default_language;
      if (args.supported_languages !== undefined) body.supported_languages = args.supported_languages;
      if (args.address !== undefined) body.address = args.address;
      const result = await apiRequest("PATCH", "/api/v1/connected_organizations/{uid}", { pathParams, body });
      return {
        content: [{
          type: "text" as const,
          text: JSON.stringify(result.data, null, 2),
        }],
      };
    } catch (error) {
      return {
        content: [{
          type: "text" as const,
          text: `Error: ${error instanceof Error ? error.message : String(error)}`,
        }],
      };
    }
  },
  async connected_organizations_delete_by_id(args) {
    try {
      const pathParams: Record<string, string> = {
        uid: String(args.uid),
      };
      const result = await apiRequest("DELETE", "/api/v1/connected_organizations/{uid}", { pathParams });
      return {
        content: [{
          type: "text" as const,
          text: JSON.stringify(result.data, null, 2),
        }],
      };
    } catch (error) {
      return {
        content: [{
          type: "text" as const,
          text: `Error: ${error instanceof Error ? error.message : String(error)}`,
        }],
      };
    }
  },
};

const connected_organizationsTools: ToolModule = { definitions, handlers };
export default connected_organizationsTools;
